/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Public } from "../../decorators/public.decorator";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateClinicArgs } from "./CreateClinicArgs";
import { UpdateClinicArgs } from "./UpdateClinicArgs";
import { DeleteClinicArgs } from "./DeleteClinicArgs";
import { ClinicFindManyArgs } from "./ClinicFindManyArgs";
import { ClinicFindUniqueArgs } from "./ClinicFindUniqueArgs";
import { Clinic } from "./Clinic";
import { ScheduleFindManyArgs } from "../../schedule/base/ScheduleFindManyArgs";
import { Schedule } from "../../schedule/base/Schedule";
import { ClinicService } from "../clinic.service";

@graphql.Resolver(() => Clinic)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class ClinicResolverBase {
  constructor(
    protected readonly service: ClinicService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @Public()
  @graphql.Query(() => MetaQueryPayload)
  async _clinicsMeta(
    @graphql.Args() args: ClinicFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @Public()
  @graphql.Query(() => [Clinic])
  async clinics(@graphql.Args() args: ClinicFindManyArgs): Promise<Clinic[]> {
    return this.service.findMany(args);
  }

  @Public()
  @graphql.Query(() => Clinic, { nullable: true })
  async clinic(
    @graphql.Args() args: ClinicFindUniqueArgs
  ): Promise<Clinic | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Clinic)
  @nestAccessControl.UseRoles({
    resource: "Clinic",
    action: "create",
    possession: "any",
  })
  async createClinic(@graphql.Args() args: CreateClinicArgs): Promise<Clinic> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Clinic)
  @nestAccessControl.UseRoles({
    resource: "Clinic",
    action: "update",
    possession: "any",
  })
  async updateClinic(
    @graphql.Args() args: UpdateClinicArgs
  ): Promise<Clinic | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Clinic)
  @nestAccessControl.UseRoles({
    resource: "Clinic",
    action: "delete",
    possession: "any",
  })
  async deleteClinic(
    @graphql.Args() args: DeleteClinicArgs
  ): Promise<Clinic | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @Public()
  @graphql.ResolveField(() => [Schedule])
  async schedules(
    @graphql.Parent() parent: Clinic,
    @graphql.Args() args: ScheduleFindManyArgs
  ): Promise<Schedule[]> {
    const results = await this.service.findSchedules(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
